# Generated by Django 3.2.6 on 2021-11-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='gaId',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
