# Generated by Django 3.2.6 on 2021-11-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_campaign_gaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='accountName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='fbId',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
