# Generated by Django 3.2.6 on 2021-11-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_clientid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indiegogo',
            fields=[
                ('jsondata', models.JSONField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
