# Generated by Django 3.2.6 on 2021-11-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_indiegogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='indiegogo',
            name='unique',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
