# Generated by Django 3.2.6 on 2021-11-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_indiegogo_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kickstarter',
            fields=[
                ('jsondata', models.JSONField(blank=True, null=True)),
                ('unique', models.IntegerField(blank=True, default=0, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
